In [ ]:
!wget --no-check-certificate https://mcfp.felk.cvut.cz/publicDatasets/CTU-13-Dataset/CTU-13-Dataset.tar.bz2

--2020-06-16 12:25:12--  https://mcfp.felk.cvut.cz/publicDatasets/CTU-13-Dataset/CTU-13-Dataset.tar.bz2
Resolving mcfp.felk.cvut.cz (mcfp.felk.cvut.cz)... 147.32.82.194
Connecting to mcfp.felk.cvut.cz (mcfp.felk.cvut.cz)|147.32.82.194|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 1997547391 (1.9G) [application/x-bzip2]
Saving to: ‘CTU-13-Dataset.tar.bz2’

CTU-13-Dataset.tar. 100%[===================>]   1.86G  10.0MB/s    in 3m 13s  

2020-06-16 12:28:26 (9.86 MB/s) - ‘CTU-13-Dataset.tar.bz2’ saved [1997547391/1997547391]



**Extract the downloaded tar.bz2 file by using the following command:**

In [ ]:
!tar xvjf  CTU-13-Dataset.tar.bz2

CTU-13-Dataset/
CTU-13-Dataset/4/
CTU-13-Dataset/4/botnet-capture-20110815-rbot-dos.pcap
CTU-13-Dataset/4/capture20110815.binetflow
CTU-13-Dataset/4/README
CTU-13-Dataset/4/rbot.exe
CTU-13-Dataset/1/
CTU-13-Dataset/1/Neris.exe
CTU-13-Dataset/1/README.html
CTU-13-Dataset/1/capture20110810.binetflow
CTU-13-Dataset/1/botnet-capture-20110810-neris.pcap
CTU-13-Dataset/12/
CTU-13-Dataset/12/botnet-capture-20110819-bot.pcap
CTU-13-Dataset/12/capture20110819.binetflow
CTU-13-Dataset/12/README
CTU-13-Dataset/12/3d3d%3F%3F%3F%3F.xls.exe
CTU-13-Dataset/7/
CTU-13-Dataset/7/sogou_explorer_silent_1.4.0.418_2136.exe
CTU-13-Dataset/7/botnet-capture-20110816-sogou.pcap
CTU-13-Dataset/7/capture20110816-2.binetflow
CTU-13-Dataset/7/README
CTU-13-Dataset/8/
CTU-13-Dataset/8/capture20110816-3.binetflow
CTU-13-Dataset/8/QvodSetuPuls23.exe
CTU-13-Dataset/8/botnet-capture-20110816-qvod.pcap
CTU-13-Dataset/8/README
CTU-13-Dataset/5/
CTU-13-Dataset/5/botnet-capture-20110815-fast-flux.pcap
CTU-13-Dataset/5/e4f81

**Pandas** is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for **manipulating numerical tables and time series**

In [ ]:
import pandas as pd
data = pd.read_csv("/content/CTU-13-Dataset/8/capture20110816-3.binetflow")
data

StartTime  ...                                   Label
0        2011/08/16 14:23:17.316620  ...             flow=Background-TCP-Attempt
1        2011/08/16 14:25:13.585599  ...  flow=Background-Established-cmpgw-CVUT
2        2011/08/16 14:26:27.614070  ...         flow=Background-TCP-Established
3        2011/08/16 14:26:29.245037  ...         flow=Background-TCP-Established
4        2011/08/16 14:26:30.868242  ...         flow=Background-TCP-Established
...                             ...  ...                                     ...
2954225  2011/08/17 09:47:11.104593  ...         flow=Background-UDP-Established
2954226  2011/08/17 09:47:11.124201  ...         flow=Background-UDP-Established
2954227  2011/08/17 09:47:11.165013  ...         flow=Background-UDP-Established
2954228  2011/08/17 09:47:11.206812  ...         flow=Background-UDP-Established
2954229  2011/08/17 09:47:11.231725  ...         flow=Background-UDP-Established

[2954230 rows x 15 columns]

In [ ]:
data['Label'] = data.Label.str.contains("Botnet")

In [ ]:
import pandas as pd
data = pd.read_csv("/content/CTU-13-Dataset/9/capture20110817.binetflow")
#data['Label'] = data.Label.str.contains("Botnet")
data

StartTime       Dur Proto  ... TotBytes SrcBytes  Label
0        2011/08/17 12:01:12.984851  0.976560   tcp  ...      244      124  False
1        2011/08/17 12:01:15.616709  0.950668   tcp  ...      244      124  False
2        2011/08/17 12:01:23.209772  1.006908   tcp  ...      276      156  False
3        2011/08/17 12:01:24.216680  1.000400   tcp  ...      276      156  False
4        2011/08/17 12:03:27.216922  1.093291   tcp  ...      244      124  False
...                             ...       ...   ...  ...      ...      ...    ...
2087503  2011/08/17 17:12:13.795564  0.000325   udp  ...      211       74  False
2087504  2011/08/17 17:12:13.828796  0.000466   udp  ...      263       85  False
2087505  2011/08/17 17:12:13.829522  0.077026   tcp  ...     3641      431  False
2087506  2011/08/17 17:12:13.843411  0.000000   udp  ...       74       74  False
2087507  2011/08/17 17:12:13.867435  0.000000   tcp  ...       66       66  False

[2087508 rows x 15 columns]

In [ ]:
data.columns

Index(['StartTime', 'Dur', 'Proto', 'SrcAddr', 'Sport', 'Dir', 'DstAddr',
       'Dport', 'State', 'sTos', 'dTos', 'TotPkts', 'TotBytes', 'SrcBytes',
       'Label'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2087508 entries, 0 to 2087507
Data columns (total 15 columns):
 #   Column     Dtype  
---  ------     -----  
 0   StartTime  object 
 1   Dur        float64
 2   Proto      object 
 3   SrcAddr    object 
 4   Sport      object 
 5   Dir        object 
 6   DstAddr    object 
 7   Dport      object 
 8   State      object 
 9   sTos       float64
 10  dTos       float64
 11  TotPkts    int64  
 12  TotBytes   int64  
 13  SrcBytes   int64  
 14  Label      object 
dtypes: float64(3), int64(3), object(9)
memory usage: 238.9+ MB


**Before training the model, we need to build some scripts to prepare the data**

In [ ]:
class Prepare(threading.Thread):
    
    def __init__(self, X, Y, XT, YT, accLabel=None):
        threading.Thread.__init__(self)
        self.X = X
        self.Y = Y
        self.XT=XT
        self.YT=YT
        self.accLabel= accLabel

    def run(self):
        X = np.zeros(self.X.shape)
        Y = np.zeros(self.Y.shape)
        XT = np.zeros(self.XT.shape)
        YT = np.zeros(self.YT.shape)
        np.copyto(X, self.X)
        np.copyto(Y, self.Y)
        np.copyto(XT, self.XT)
        np.copyto(YT, self.YT)
        for i in range(9):
            X[:, i] = (X[:, i] - X[:, i].mean()) / (X[:, i].std())  #data Standardization
#standardization rescales data to have a mean of 0 and standard of 1(1unit variance) --- X(changed)=[X-mean]/SD
#Standardized values are useful for tracking data that isn't easy to compare otherwise.
        for i in range(9):
            XT[:, i] = (XT[:, i] - XT[:, i].mean()) / (XT[:, i].std())

LoadData.py directly in your projects to load data from .binetflow files and generate a pickle file.

Socket programming - way of connecting 2 nodes on a network. One socket(node) listens to a particular port at an IP, while the other reaches out to other to form a connection. Server---forms the listener socket while client reaches out to the screen.
-------------------------------------------------------------------------------
The pickle module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a binary file or bytes-like object) is converted back into an object hierarchy.
For fast loading
-------------------------------------------------------------------------------

In [ ]:
import socket, struct, sys
import numpy as np
import pickle

def loaddata(fileName):
    

    file = open(fileName, 'r')

    xdata = []
    ydata = []
    xdataT = []
    ydataT = []
    flag=0
    count1=0
    count2=0
    count3=0
    count4=0

    #dicts to convert protocols and state to integers ---- UDP (User Datagram program) TCP(Transmission control Protocol)
    protoDict = {'arp': 5, 'unas': 13, 'udp': 1, 'rtcp': 7, 'pim': 3, 'udt': 11, 'esp': 12, 'tcp' : 0, 'rarp': 14, 'ipv6-icmp': 9, 'rtp': 2, 'ipv6': 10, 'ipx/spx': 6, 'icmp': 4, 'igmp' : 8}

    stateDict = {'': 1, 'FSR_SA': 30, '_FSA': 296, 'FSRPA_FSA': 77, 'SPA_SA': 31, 'FSA_SRA': 1181, 'FPA_R': 46, 'SPAC_SPA': 37, 'FPAC_FPA': 2, '_R': 1, 'FPA_FPA': 784, 'FPA_FA': 66, '_FSRPA': 1, 'URFIL': 431, 'FRPA_PA': 5, '_RA': 2, 'SA_A': 2, 'SA_RA': 125, 'FA_FPA': 17, 'FA_RA': 14, 'PA_FPA': 48, 'URHPRO': 380, 'FSRPA_SRA': 8, 'R_':541, 'DCE': 5, 'SA_R': 1674, 'SA_': 4295, 'RPA_FSPA': 4, 'FA_A': 17, 'FSPA_FSPAC': 7, 'RA_': 2230, 'FSRPA_SA': 255, 'NNS': 47, 'SRPA_FSPAC': 1, 'RPA_FPA': 42, 'FRA_R': 10, 'FSPAC_FSPA': 86, 'RPA_R': 3, '_FPA': 5, 'SREC_SA': 1, 'URN': 339, 'URO': 6, 'URH': 3593, 'MRQ': 4, 'SR_FSA': 1, 'SPA_SRPAC': 1, 'URP': 23598, 'RPA_A': 1, 'FRA_': 351, 'FSPA_SRA': 91, 'FSA_FSA': 26138, 'PA_': 149, 'FSRA_FSPA': 798, 'FSPAC_FSA': 11, 'SRPA_SRPA': 176, 'SA_SA': 33, 'FSPAC_SPA': 1, 'SRA_RA': 78, 'RPAC_PA': 1, 'FRPA_R': 1, 'SPA_SPA': 2989, 'PA_RA': 3, 'SPA_SRPA': 4185, 'RA_FA': 8, 'FSPAC_SRPA': 1, 'SPA_FSA': 1, 'FPA_FSRPA': 3, 'SRPA_FSA': 379, 'FPA_FRA': 7, 'S_SRA': 81, 'FSA_SA': 6, 'State': 1, 'SRA_SRA': 38, 'S_FA': 2, 'FSRPAC_SPA': 7, 'SRPA_FSPA': 35460, 'FPA_A': 1, 'FSA_FPA': 3, 'FRPA_RA': 1, 'FSAU_SA': 1, 'FSPA_FSRPA': 10560, 'SA_FSA': 358, 'FA_FRA': 8, 'FSRPA_SPA': 2807, 'FSRPA_FSRA': 32, 'FRA_FPA': 6, 'FSRA_FSRA': 3, 'SPAC_FSRPA': 1, 'FS_': 40, 'FSPA_FSRA': 798, 'FSAU_FSA': 13, 'A_R': 36, 'FSRPAE_FSPA': 1, 'SA_FSRA': 4, 'PA_PAC': 3, 'FSA_FSRA': 279, 'A_A': 68, 'REQ': 892, 'FA_R': 124, 'FSRPA_SRPA': 97, 'FSPAC_FSRA':20, 'FRPA_RPA': 7, 'FSRA_SPA': 8, 'INT': 85813, 'FRPA_FRPA': 6, 'SRPAC_FSPA': 4, 'SPA_SRA': 808, 'SA_SRPA': 1, 'SPA_FSPA': 2118, 'FSRAU_FSA': 2, 'RPA_PA': 171,'_SPA': 268, 'A_PA': 47, 'SPA_FSRA': 416, 'FSPA_FSRPAC': 2, 'PAC_PA': 5, 'SRPA_SPA': 9646, 'SRPA_FSRA': 13, 'FPA_FRPA': 49, 'SRA_SPA': 10, 'SA_SRA': 838, 'PA_PA': 5979, 'FPA_RPA': 27, 'SR_RA': 10, 'RED': 4579, 'CON': 2190507, 'FSRPA_FSPA':13547, 'FSPA_FPA': 4, 'FAU_R': 2, 'ECO': 2877, 'FRPA_FPA': 72, 'FSAU_SRA': 1, 'FRA_FA': 8, 'FSPA_FSPA': 216341, 'SEC_RA': 19, 'ECR': 3316, 'SPAC_FSPA': 12, 'SR_A': 34, 'SEC_': 5, 'FSAU_FSRA': 3, 'FSRA_FSRPA': 11, 'SRC': 13, 'A_RPA': 1, 'FRA_PA': 3, 'A_RPE': 1, 'RPA_FRPA': 20, '_SRA': 74, 'SRA_FSPA': 293, 'FPA_': 118, 'FSRPAC_FSRPA': 2, '_FA': 1, 'DNP': 1, 'FSRPA_FSRPA': 379, 'FSRA_SRA': 14, '_FRPA': 1, 'SR_': 59, 'FSPA_SPA': 517, 'FRPA_FSPA': 1, 'PA_A': 159, 'PA_SRA': 1, 'FPA_RA': 5, 'S_': 68710, 'SA_FSRPA': 4, 'FSA_FSRPA': 1, 'SA_SPA': 4, 'RA_A': 5, '_SRPA': 9, 'S_FRA': 156, 'FA_FRPA': 1, 'PA_R': 72, 'FSRPAEC_FSPA': 1, '_PA': 7, 'RA_S': 1, 'SA_FR': 2, 'RA_FPA': 6, 'RPA_': 5, '_FSPA': 2395, 'FSA_FSPA': 230, 'UNK': 2, 'A_RA': 9, 'FRPA_': 6, 'URF': 10, 'FS_SA': 97, 'SPAC_SRPA': 8, 'S_RPA': 32, 'SRPA_SRA': 69, 'SA_RPA': 30, 'PA_FRA': 4, 'FSRA_SA': 49, 'FSRA_FSA': 206, 'PAC_RPA': 1, 'SRA_': 18, 'FA_': 451, 'S_SA': 6917, 'FSPA_SRPA': 427, 'TXD': 542,'SRA_SA': 1514, 'FSPA_FA': 1, 'FPA_FSPA': 10, 'RA_PA': 3, 'SRA_FSA': 709, 'SRPA_SPAC': 3, 'FSPAC_FSRPA': 10, 'A_': 191, 'URNPRO': 2, 'PA_RPA': 81, 'FSPAC_SRA':1, 'SRPA_FSRPA': 3054, 'SPA_': 1, 'FA_FA': 259, 'FSPA_SA': 75, 'SR_SRA': 1, 'FSA_': 2, 'SRPA_SA': 406, 'SR_SA': 3119, 'FRPA_FA': 1, 'PA_FRPA': 13, 'S_R': 34, 'FSPAEC_FSPAE': 3, 'S_RA': 61105, 'FSPA_FSA': 5326, '_SA': 20, 'SA_FSPA': 15, 'SRPAC_SPA': 8, 'FPA_PA': 19, 'FSRPAE_FSA': 1, 'S_A': 1, 'RPA_RPA': 3, 'NRS': 6, 'RSP': 115, 'SPA_FSRPA': 1144, 'FSRPAC_FSPA': 139}

    file.readline()

    for line in file:
        sd = line[:-1].split(',') ##Each line ends with the newline-symbol. #
                                  #That's why you cut away the last symbol with line[:-1].
                ##The numbers are separated by commas, so you take this line and cut/split it at each comma with line[:-1].split(',').
        ##features that are being considered --- 10
        dur, proto, Sport, Dport, Sip, Dip, totP, totB, label, state = sd[1], sd[2], sd[4], sd[7], sd[3], sd[6], sd[-4], sd[-3], sd[-1], sd[8]
        try:
            Sip = socket.inet_aton(Sip)         ##one socket node listens on a particular port at an IP---Source IP
            Sip = struct.unpack("!L", Sip)[0]  
            #struct -- This can be used in handling binary data stored in files or from network connections, among other sources
            #By default, the result of packing a given python struct includes pad bytes in order to maintain proper alignment for the python types involved; 
            #similarly, alignment is taken into account when unpacking
        except:
            continue
        try:
            Dip = socket.inet_aton(Dip)         ##one socket node listens on a particular port at an IP---Destination IP
            Dip = struct.unpack("!L", Dip)[0]   ## unwrapping the struct 
        except:
            continue
        if Sport=='': continue
        if Dport=='': continue
        #back, nor, bot
        try:

            if "Background" in label:
                label=0

            elif "Normal" in label:
                label = 0

            elif "Botnet" in label:
                label = 1


            if flag==0:
                #Training Dataset
                if label==0 and count1<20001:
                    xdata.append([float(dur), protoDict[proto], int(Sport), int(Dport), Sip, Dip, int(totP), int(totB), stateDict[state]])
                    ydata.append(label)
                    count1+=1

                elif label==1 and count2<20001:
                    xdata.append([float(dur), protoDict[proto], int(Sport), int(Dport), Sip, Dip, int(totP), int(totB), stateDict[state]])
                    ydata.append(label)
                    count2+=1

                elif count1>19999 and count2>19999:
                    #print("HI")
                    flag=1

            else:
                #Test dataset
                if label==0 and count3<5001:
                    #print("H")
                    xdataT.append([float(dur), protoDict[proto], int(Sport), int(Dport), Sip, Dip, int(totP), int(totB), stateDict[state]])
                    ydataT.append(label)
                    count3+=1
                elif label==1 and count4<5001:
                    xdataT.append([float(dur), protoDict[proto], int(Sport), int(Dport), Sip, Dip, int(totP), int(totB), stateDict[state]])
                    ydataT.append(label)
                    count4 += 1
                elif count3>4999 and count4>4999:
                    break
        except:
            continue

    #pickle the dataset for fast loading  ----- like in java---serializing object into bytes while storing
    file = open('flowdata.pickle', 'wb')
    pickle.dump([np.array(xdata), np.array(ydata), np.array(xdataT), np.array(ydataT)], file)

    #return the training and the test dataset

    return np.array(xdata), np.array(ydata), np.array(xdataT), np.array(ydataT)

if __name__ == "__main__":
    loaddata('/content/CTU-13-Dataset/9/capture20110817.binetflow')

In [ ]:
import pickle
file = open('flowdata.pickle', 'rb')  ------ like deserializing the bytes into object 
data  = pickle.load(file)
#Select the data sections:
Xdata = data[0]
Ydata =  data[1]
XdataT = data[2]
YdataT = data[3]

In [ ]:
Xdata.shape

(40001, 9)

In [ ]:
XdataT.shape

(10001, 9)

In [ ]:
Ydata.shape

(40001,)

In [ ]:
YdataT.shape

(10001,)

In [ ]:
XdataT

array([[1.880000e-04, 1.000000e+00, 5.932700e+04, ..., 2.000000e+00,
        2.140000e+02, 2.190507e+06],
       [2.380000e-04, 1.000000e+00, 3.665900e+04, ..., 2.000000e+00,
        2.140000e+02, 2.190507e+06],
       [2.630000e-04, 1.000000e+00, 4.033900e+04, ..., 2.000000e+00,
        2.140000e+02, 2.190507e+06],
       ...,
       [0.000000e+00, 0.000000e+00, 3.575000e+03, ..., 1.000000e+00,
        6.200000e+01, 6.871000e+04],
       [1.473169e+00, 0.000000e+00, 2.679000e+03, ..., 2.500000e+01,
        1.305600e+04, 2.163410e+05],
       [4.810000e-04, 1.000000e+00, 1.491000e+03, ..., 2.000000e+00,
        3.170000e+02, 2.190507e+06]])

In [ ]:
Xdata

array([[9.7656000e-01, 0.0000000e+00, 2.2540000e+03, ..., 4.0000000e+00,
        2.4400000e+02, 6.1105000e+04],
       [9.5066800e-01, 0.0000000e+00, 6.4136000e+04, ..., 4.0000000e+00,
        2.4400000e+02, 6.1105000e+04],
       [1.0069080e+00, 0.0000000e+00, 3.8440000e+03, ..., 4.0000000e+00,
        2.7600000e+02, 6.1105000e+04],
       ...,
       [1.1748079e+01, 0.0000000e+00, 2.3400000e+03, ..., 1.0000000e+01,
        1.3260000e+03, 3.5460000e+04],
       [4.6680000e-02, 1.0000000e+00, 1.5970000e+03, ..., 2.0000000e+00,
        3.2300000e+02, 2.1905070e+06],
       [8.9325760e+00, 0.0000000e+00, 1.5500000e+03, ..., 3.0000000e+00,
        1.8600000e+02, 6.8710000e+04]])

In [ ]:
Ydata

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
YdataT

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
from sklearn.linear_model import *
from sklearn.tree import *
from sklearn.naive_bayes import *
from sklearn.neighbors import *

In [ ]:
class Prepare(threading.Thread):
    
    def __init__(self, X, Y, XT, YT, accLabel=None):
        threading.Thread.__init__(self)
        self.X = X
        self.Y = Y
        self.XT=XT
        self.YT=YT
        self.accLabel= accLabel

    def run(self):
        X = np.zeros(self.X.shape)
        Y = np.zeros(self.Y.shape)
        XT = np.zeros(self.XT.shape)
        YT = np.zeros(self.YT.shape)
        np.copyto(X, self.X)
        np.copyto(Y, self.Y)
        np.copyto(XT, self.XT)
        np.copyto(YT, self.YT)
        for i in range(9):
            X[:, i] = (X[:, i] - X[:, i].mean()) / (X[:, i].std()) 
        for i in range(9):
            XT[:, i] = (XT[:, i] - XT[:, i].mean()) / (XT[:, i].std())

In [ ]:
Prepare(Xdata,Ydata,XdataT,YdataT)

<Prepare(Thread-4, initial)>

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(Xdata,Ydata)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
Prediction = clf.predict(XdataT)


NameError: ignored

In [ ]:
Prediction = clf.predict(XdataT)
Score = clf.score(XdataT,YdataT)
print ("The Score of the Decision Tree Classifier is", Score * 100)

The Score of the Decision Tree Classifier is 99.89001099890011


In [ ]:
clf = LogisticRegression(C=10000)
clf.fit(Xdata,Ydata)
Prediction = clf.predict(XdataT)
Prediction
#Score = clf.score(XdataT,YdataT)

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
Score = clf.score(XdataT,YdataT)
print ("The Score of the Logistic Regression Classifier is", Score * 100)

The Score of the Logistic Regression Classifier is 96.25037496250374


**Gaussian Naive Bayes model:**

In [ ]:
clf = GaussianNB()
clf.fit(Xdata,Ydata)
Prediction = clf.predict(XdataT)
Score = clf.score(XdataT,YdataT)
print("The Score of the Gaussian Naive Bayes classifier is", Score * 100)

The Score of the Gaussian Naive Bayes classifier is 67.83321667833216


In [ ]:
clf = KNeighborsClassifier()
clf.fit(Xdata,Ydata)
Prediction = clf.predict(XdataT)
Score = clf.score(XdataT,YdataT)
print("The Score of the K-Nearest Neighbours classifier is", Score * 100)

The Score of the K-Nearest Neighbours classifier is 96.84031596840316
